#!/usr/bin/env bash

if [ -f .initialized ]; then
  echo 'Drupal is already initialized.'
else
  touch .initialized

  # If we get this far, move Drupal files in place.
  mv /html/* /html/.htaccess /var/www/html
fi

gotpl /etc/gotpl/settings.php.tpl > sites/default/settings.php
chown www-data:www-data sites/default/settings.php

apache2-foreground
