<?php
// $Id: markdownpreview.module,v 1.4.2.2 2009/04/10 08:26:32 henrrrik Exp $

/**
 * @file
 * A Markdown preview pane for textarea form fields
 */


/**
 * Implementation of hook_perm().
 */
function markdownpreview_perm() {
  return array('use markdown preview');
}

/**
 * Implementation of hook_menu().
 */
function markdownpreview_menu() {
  $items = array();
  $items['admin/settings/markdownpreview'] = array(
    'title' => 'Markdown Preview',
    'description' => 'Provides a Markdown preview pane for textarea fields.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('markdownpreview_settings_form'),
  );
  return $items;
}

function markdownpreview_settings_form() {

  $form['markdownpreview_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['markdownpreview_settings']['markdownpreview_include'] = array(
    '#type' => 'textarea',
    '#title' => t('Textarea fields that should feature a preview pane'),
    '#cols' => 60,
    '#rows' => 5,
    '#default_value' => variable_get("markdownpreview_include", 'edit-body,edit-teaser-js'),
    '#description' => t("id attributes of textarea input tags that should use a preview pane (separated by commas, spaces or newlines). Example: <em>edit-body</em> for all node Body fields."),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_elements().
 */
function markdownpreview_elements() {
  // If Markdown Preview for BUEditor is installed and the user is permitted to use it, use that instead.
  if (user_access('use markdown preview') && (!module_exists('markdownpreview_bueditor') || (module_exists('markdownpreview_bueditor') && !user_access('use markdown preview for bueditor')))) {
    return array('textarea' => array(
      '#process' => array('markdownpreview_process_textarea'),
      ),
    );
  }
  return $type;
}

/**
 * Implementation of hook_theme().
 */
function markdownpreview_theme() {
  return array(
    'markdownpreview_field' => array('arguments' => array('element' => NULL)),
  );
}

function markdownpreview_process_textarea($element) {
  // regexp courtesy of FCKeditor module
  $include = preg_split("/[\s,]+/", strip_tags(variable_get("markdownpreview_include", '')));

  if (in_array($element['#id'], $include)) {
    if ($element['#attributes']['class']) {
      $element['#attributes']['class'] .= ' markdown-preview';
    }
    else {
      $element['#attributes']['class'] = 'markdown-preview';
    }
    drupal_add_css(drupal_get_path('module', 'markdownpreview') .'/markdownpreview.css');
    // Don't preprocess these.
    drupal_add_js(drupal_get_path('module', 'markdownpreview') .'/../showdown/showdown.js', 'module', 'footer', FALSE, TRUE, FALSE);
    drupal_add_js(drupal_get_path('module', 'markdownpreview') .'/markdownpreview.js', 'module', 'footer', FALSE, TRUE, FALSE);
  }
  else if (user_access('administer site configuration') && $element['#id'] != 'edit-markdownpreview-include' && !isset($element['#teaser'])) {
    $element['#suffix'] = '<span class="markdownpreview-id">'. t('Use markdown previews for @title content by including this id: %id', array('@title' => $element['#title'], '%id' => $element['#id'])) .'</span>';
  }
  return $element;
}

/**
 * Implementation of hook_requirements().
 */
function markdownpreview_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    if (!file_exists(drupal_get_path('module', 'markdownpreview') .'/../showdown/showdown.js')) {
      $requirements['markdownpreview'] = array(
        'title' => t('Showdown'),
        'description' => t('<strong>showdown.js</strong> has not been installed in the directory <em>markdownpreview/showdown</em>. <strong>Markdown Preview</strong> cannot function without it.'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Not installed'),
      );
    }
  }

  return $requirements;
}
