<?php
// $Id: markdownpreview_bueditor.module,v 1.4.2.2 2009/04/10 08:26:33 henrrrik Exp $

/**
 * @file
 * A Markdown preview pane for BUEditor
 */


function markdownpreview_bueditor_textarea($element) {
  if (user_access('use markdown preview for bueditor')) {
    global $user;
    static $editors;

    // We use BUEditor's detection functions to figure out whether we should insert the JS.
    if (!isset($editors)) {
      $editors = bueditor_user_eids($user);
    }
    $bueditor = bueditor_check_page($_GET['q'], $editors[0]);

    if ($editors[0] && !bueditor_check_match($bueditor->excludes, $element['#id']) && in_array($bueditor->eid, variable_get('markdownpreview_bueditor_editors', array()))) {
      drupal_add_css(drupal_get_path('module', 'markdownpreview_bueditor') .'/markdownpreview_bueditor.css');
      // Don't preprocess these.
      drupal_add_js(drupal_get_path('module', 'markdownpreview_bueditor') .'/../showdown/showdown.js', 'module', 'footer', FALSE, TRUE, FALSE);
      drupal_add_js(drupal_get_path('module', 'markdownpreview_bueditor') .'/markdownpreview_bueditor.js', 'module', 'footer', FALSE, TRUE, FALSE);
    }
  }
  return $element;
}

/**
 * Implementation of hook_elements().
 */
function markdownpreview_bueditor_elements() {
  return array('textarea' => array('#process' => array('markdownpreview_bueditor_textarea')));
}


/**
 * Implementation of hook_perm().
 */
function markdownpreview_bueditor_perm() {
  return array('use markdown preview for bueditor');
}

/**
 * Implementation of hook_menu().
 */
function markdownpreview_bueditor_menu() {
  $items = array();
  $items['admin/settings/markdownpreview_bueditor'] = array(
    'title' => 'Markdown Preview for BUEditor',
    'description' => 'Provides a Markdown preview pane for BUEditor.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('markdownpreview_bueditor_settings_form'),
  );
  return $items;
}

function markdownpreview_bueditor_settings_form() {

  $result = db_query("SELECT eid, name FROM {bueditor_editors}");

  while ($editor = db_fetch_object($result)) {
    $options[$editor->eid] = $editor->name;
  }

  $form['markdownpreview_bueditor_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['markdownpreview_bueditor_settings']['markdownpreview_bueditor_editors'] = array(
    '#title' => t('Editors to enable markdown previews for'),
    '#type' => 'checkboxes',
    '#description' => t('Select the BUEditor editor configurations that you wish to enable markdown previews for.'),
    '#options' => $options,
    '#default_value' => variable_get('markdownpreview_bueditor_editors', array()),
    '#weight' => 25,
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_requirements().
 */
function markdownpreview_bueditor_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    if (!file_exists(drupal_get_path('module', 'markdownpreview_bueditor') .'/../showdown/showdown.js')) {
      $requirements['markdownpreview_bueditor'] = array(
        'title' => t('Showdown'),
        'description' => t('<strong>showdown.js</strong> has not been installed in the directory <em>markdownpreview/showdown</em>. <strong>Markdown Preview for BUEditor</strong> cannot function without it.'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Not installed'),
      );
    }
  }
  return $requirements;
}

